[0m16:08:06.509113 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x743925ec07a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x743925153200>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x743925968bc0>]}


============================== 16:08:06.513391 | 19b4f68e-df7e-4a3d-8718-7bd01c1d9202 ==============================
[0m16:08:06.513391 [info ] [MainThread]: Running with dbt=1.10.13
[0m16:08:06.513918 [debug] [MainThread]: running dbt with arguments {'quiet': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'partial_parse': 'True', 'use_colors': 'True', 'invocation_command': 'dbt run', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'version_check': 'True', 'cache_selected_only': 'False', 'use_experimental_parser': 'False', 'printer_width': '80', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'log_format': 'default', 'log_path': 'logs', 'empty': 'False', 'static_parser': 'True', 'target_path': 'None', 'send_anonymous_usage_stats': 'True', 'write_json': 'True', 'introspect': 'True', 'profiles_dir': '/root/.dbt'}
[0m16:08:06.514634 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/ubuntu/real-time-stocks-mds/dags/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:08:06.515532 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.059419163, "process_in_blocks": "0", "process_kernel_time": 0.100578, "process_mem_max_rss": "99352", "process_out_blocks": "8", "process_user_time": 1.154127}
[0m16:08:06.515935 [debug] [MainThread]: Command `dbt run` failed at 16:08:06.515853 after 0.06 seconds
[0m16:08:06.516214 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x74392558b770>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x743926152ae0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7439253b74a0>]}
[0m16:08:06.516529 [debug] [MainThread]: Flushing usage events
[0m16:08:06.548693 [debug] [MainThread]: An error was encountered while trying to flush usage events
